# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25bd2b85556c9e9ae60b61fc021203ae44fee60e4b761242c0a245db084a4828bca2e640790569b602e7f082bc6e8c2afcdc57654c382be7fab27f49abf3e297

test:
  secret_key_base: c6ad5389fc4696bfb16a4296cbad37736c1b8f3263990b4d91c7fefc702ad27fc6e37909692577a2003212bbebe07a38d6d7d6eea31b6c73d778be6483a456e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
